version: '3'
services: 
    web:
        container_name: flight-web-app
        build:
            context: .
            dockerfile: 
             .Dockerfile-prod
        environment:
            PRODUCTION: 'true'
        ports: 
            - '3001:80'
