version: '3'
services: 
    web:
        container_name: flight-web-app
        build:
            context: .
            dockerfile: 
             prod.Dockerfile
        environment:
            PRODUCTION: 'true'
        restart: always
        ports: 
            - '3001:80'
    
