version: '3'
services: 
    app:
        container_name: flight-app
        restart: always
        build:
            context: .
        ports: 
            - '3000:3000'
        command: yarn start
        environment: 
            DEVELOPEMENT: 'true'
        volumes: 
            - './flightapp'

    test:
        build:  
            context: ./docker
        environment: 
            - CI=true
        command: yarn test
       