version: '3'
services: 
    app:
        container_name: flight-app
        restart: always
        build:
            context: .
        ports: 
            - '3000:3000'
        command: yarn start
        environment: 
            DEVELOPEMENT: 'true'
        volumes: 
            - 'app_app:/flightapp'

    test:
        build:  
            context: .
        environment: 
            - CI=true
        command: yarn test

    db:
        image: 'postgres'
        env_file: 
            - .db.env
        container_name: flight-database
        ports:
            - '54320:5432'
        volumes: 
            - my_flightdata:/var/lib/postgresql/data
volumes:
    my_flightdata:
    app_app:
        